

# 넘파이 (numpy)

In [1]:
# 필요한 라이브러리 임포트
import numpy as np

## 넘파이 배열과 파이썬 리스트 비교

In [2]:
# 파이썬 리스트 자료 구조 데이터 생성
list_data =[1,2,3]
print(f'파이썬 리스트:{list_data}')

print('-'*80)

#넘파이 배열 생성
array_data=np.array(list_data)
print(f'넘파이 배열:{array_data}')

파이썬 리스트:[1, 2, 3]
--------------------------------------------------------------------------------
넘파이 배열:[1 2 3]

In [3]:
# 파이썬 리스트와 넘파이 배열의 차이점 확인

## 덧셈 연산

### 파이썬 리스트
result1 = list_data + list_data
print(f'파이썬 리스트에 대한  덧셈 연산의 결과: \n{result1}')

print('-'*80)

### 넘파이 배열
result2 = array_data + array_data
print(f'넘파이 배열에 대한 덧셈 연산의 결과: \n{result2}')

print('-'*80)

##곱셈 연산

### 파이썬 리스트
result3=[]
for i in list_data:
    result3.append(i*3)

print(f'파이썬 리스트에 대한 곱셈 연산의 결과: \n{result3}')

print('-'*80)

### 넘파이 배열 (<- 여러번 연산해야할 것을 한번에 가능하게 함)
result4 = array_data * 3
print(f'넘파이 배열에 대한 곱셈 연산의 결과: \n{result4}')

print('-'*80)

파이썬 리스트에 대한  덧셈 연산의 결과:
[1, 2, 3, 1, 2, 3]
--------------------------------------------------------------------------------
넘파이 배열에 대한 덧셈 연산의 결과:
[2 4 6]
--------------------------------------------------------------------------------
파이썬 리스트에 대한 곱셈 연산의 결과:
[3, 6, 9]
--------------------------------------------------------------------------------
넘파이 배열에 대한 곱셈 연산의 결과:
[3 6 9]
--------------------------------------------------------------------------------

In [4]:
## 통계 처리 (평균값 구하기)

### 파이썬 리스트
list_average = sum(list_data)/len(list_data)
print(f'파이썬 리스트에 대한 평균값: {list_average}')

print('-'*80)

### 넘파이 배열
array_average = np.mean(array_data)
print(f'넘파이 배열에 대한 평균값: {array_average}')
array_average = array_data.mean()
print(f'넘파이 배열에 대한 평균값: {array_average}')

파이썬 리스트에 대한 평균값: 2.0
--------------------------------------------------------------------------------
넘파이 배열에 대한 평균값: 2.0
넘파이 배열에 대한 평균값: 2.0

In [5]:
# 대괄호가 중첩된 리스트 자료 구조 데이터 생성 (조건: 성분 원소의 개수가 동일할 것)
list_data = [[1,2,3],[4,5,6],[7,8,9]]
print (f'대괄호가 중첩된 리스트 자료구조 데이터 확인 : \n{list_data}')

print('-'*80)

# 넘파이 배열로 변환
array_data = np.array(list_data)
print(f'대괄호가 중첩된 리스트를 넘파이 배열로 변환한 결과: \n{array_data}')

대괄호가 중첩된 리스트 자료구조 데이터 확인 :
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
--------------------------------------------------------------------------------
대괄호가 중첩된 리스트를 넘파이 배열로 변환한 결과:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

## 2차원 배열 생성

In [6]:
# 대괄호가 중첩된 리스트 자료 구조 데이터 생성 (조건: 성분 원소의 개수가 동일할 것)
list_data = [[1,2,3],[4,5,6]]
print (f'대괄호가 중첩된 리스트 자료구조 데이터 확인 : \n{list_data}')

print('-'*80)

# 넘파이 배열로 변환 -> 2차원 배열 -> 엑셀과 같은 표(행과 열) 구조 생성
array_data = np.array(list_data)
print(f'대괄호가 중첩된 리스트를 넘파이 배열로 변환한 결과: \n{array_data}')

대괄호가 중첩된 리스트 자료구조 데이터 확인 :
[[1, 2, 3], [4, 5, 6]]
--------------------------------------------------------------------------------
대괄호가 중첩된 리스트를 넘파이 배열로 변환한 결과:
[[1 2 3]
 [4 5 6]]

## 인덱싱

In [7]:
# 목표: 첫번째 행, 첫번째 열-> 1 추출

## 1단계: 첫번째 행 추출 -> 변수[인덱스] -> 첫번째 행 추출
result=array_data[0]
print(f'첫번째 행 추출 결과: \n{result}')

print('-'*80)

## 2단계: 파이썬 방식 -> 변수[인덱스] -> 첫번째 성분(첫번째 열) 원소
# result2 = result1[0]
result2 = array_data[0][0]
print(result2)

print('-'*80)
## 넘파이 방식 : 넘파이의 배열 모양(2행,3열) 이용 -> 변수 [행 인덱스, 열 인덱스]
result3 = array_data[0,0]
print(f'숫자 1을 인덱싱한 결과: {result3}')

첫번째 행 추출 결과:
[1 2 3]
--------------------------------------------------------------------------------
1
--------------------------------------------------------------------------------
숫자 1을 인덱싱한 결과: 1

# 3/26 넘파이 라이브러리 복습문제

In [8]:
# 문제1 배열 생성 및 덧셈 연산
arr1=np.array([10,20,30])
arr2= np.array([1,2,3])

print(f'결과:{arr1+arr2}')

결과:[11 22 33]

In [9]:
# 문제 2 곱셈 연산
data = [5,10,15]
arr_data = np.array(data)
multi=arr_data*3

print(f'배열 곱셈 결과:{multi}')

배열 곱셈 결과:[15 30 45]

In [10]:
# 문제 3 평균값 구하기
arr = np.array([10, 30, 50, 70, 90])

print(f'평균값:{arr.mean()}')

평균값:50.0

In [11]:
# 문제 4 2차원 배열 생성
list=[[10,20],[30,40]]
arr_list=np.array(list)

print(f'2차원 배열 생성 결과:\n {arr_list}')

2차원 배열 생성 결과:
 [[10 20]
 [30 40]]

In [12]:
# 문제 5 2차원 배열 인덱싱
#위의 arr_list에서 숫자 40을 추출하고자해.
#넘파이의 행,열을 이용한 인덱싱 방식으로 코드 작성해줘
print(f'추출된 숫자: {arr_list[1, 1]}')

추출된 숫자: 40

# 판다스(pandas)

In [13]:
# 필요한 라이브러리 임폴트
import pandas as pd

## DataFrame 자료 구조 생성:csv 파일 처리

In [14]:
# colab과 구글드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [15]:
# DataFrame 생성

## 파일 경로(위치) 설정
file_path ="/content/drive/MyDrive/KDT/ad_performance.csv"

## pd.read_csv() 호출
df= pd.read_csv(file_path)

## 결과 학인
# print(df)
display(df)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303
3,2025-01-01,Organic,30s,Female,6866,686,81358,28,520546
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721
...,...,...,...,...,...,...,...,...,...
4995,2025-06-29,Organic,20s,Female,10064,933,180066,40,814096
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452
4997,2025-06-29,Organic,40s,Male,7331,378,159162,20,795243
4998,2025-06-29,Google,20s,Male,9272,124,173437,23,1293372
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870

## 분해

In [16]:
# 행 인덱스 추출
info_index= df.index
print(f'DatrFrame의 행 인덱스 :\n {info_index}')

print('-'*80)

#컬럼 인덱스 추출
info_columns = df.columns
print(f'DatrFrame의 컬럼 인덱스 :\n {info_columns}')

print('-'*80)

# 값 추출
info_values = df.values
print(f'DatrFrame의 값 :\n {info_values}')

DatrFrame의 행 인덱스 :
 RangeIndex(start=0, stop=5000, step=1)
--------------------------------------------------------------------------------
DatrFrame의 컬럼 인덱스 :
 Index(['Date', 'Channel', 'Age_Group', 'Gender', 'Impressions', 'Clicks',
       'Cost', 'Conversions', 'Revenue'],
      dtype='object')
--------------------------------------------------------------------------------
DatrFrame의 값 :
 [['2025-01-01' 'Facebook' '50s+' ... 100308 27 723225]
 ['2025-01-01' 'Google' '20s' ... 103029 26 1680444]
 ['2025-01-01' 'Naver' '50s+' ... 158046 48 1580303]
 ...
 ['2025-06-29' 'Organic' '40s' ... 159162 20 795243]
 ['2025-06-29' 'Google' '20s' ... 173437 23 1293372]
 ['2025-06-29' 'Naver' '30s' ... 193294 13 1000870]]

## 인덱싱

In [17]:
# 특정 컬럼 인덱싱
channel = df["Channel"]
print(channel)

0       Facebook
1         Google
2          Naver
3        Organic
4          Naver
          ...
4995     Organic
4996       Naver
4997     Organic
4998      Google
4999       Naver
Name: Channel, Length: 5000, dtype: object

In [18]:
#fancy 인덱싱: 변수[['컬럼1', '컬럼 4','컬럼3',...]]
df1 = df[['Channel','Clicks','Revenue']]

print(df1)

       Channel  Clicks  Revenue
0     Facebook     578   723225
1       Google     897  1680444
2        Naver     471  1580303
3      Organic     686   520546
4        Naver     525  1505721
...        ...     ...      ...
4995   Organic     933   814096
4996     Naver     537   256452
4997   Organic     378   795243
4998    Google     124  1293372
4999     Naver     733  1000870

[5000 rows x 3 columns]

In [19]:
print(df['Clicks'])
print('-'*80)
print(df['Impressions'])

print('-'*80)
print(df['Clicks']/df['Impressions'])

0       578
1       897
2       471
3       686
4       525
       ...
4995    933
4996    537
4997    378
4998    124
4999    733
Name: Clicks, Length: 5000, dtype: int64
--------------------------------------------------------------------------------
0       15412
1       11990
2       18503
3        6866
4        5250
        ...
4995    10064
4996     5657
4997     7331
4998     9272
4999    12688
Name: Impressions, Length: 5000, dtype: int64
--------------------------------------------------------------------------------
0       0.037503
1       0.074812
2       0.025455
3       0.099913
4       0.100000
          ...
4995    0.092707
4996    0.094927
4997    0.051562
4998    0.013374
4999    0.057771
Length: 5000, dtype: float64

## 새로운 컬럼 추가 (파생 변수 생성)

In [20]:
# CTR (Click-Through Rate): 클릭률
df['CTR']= df['Clicks']/df['Impressions']*100
display(df)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CTR
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225,3.750324
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444,7.481234
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303,2.545533
3,2025-01-01,Organic,30s,Female,6866,686,81358,28,520546,9.991261
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721,10.000000
...,...,...,...,...,...,...,...,...,...,...
4995,2025-06-29,Organic,20s,Female,10064,933,180066,40,814096,9.270668
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452,9.492664
4997,2025-06-29,Organic,40s,Male,7331,378,159162,20,795243,5.156186
4998,2025-06-29,Google,20s,Male,9272,124,173437,23,1293372,1.337360
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870,5.777112

In [21]:
#  CPC (Cost Per Click): 클릭당 비용
df['CPC']=df['Cost']/df['Clicks']

# CVR (Conversion Rate): 전환율
df['CVR'] = df['Conversions']/df['Clicks']*100

# CPA (Cost Per Acquisition): 전환당 비용
df['CPA'] = df['Cost']/df['Conversions']

# ROAS (Return On Ad Spend): 광고비 대비 수익률
df['ROAS']= df['Revenue']/df['Cost']*100

# 최종결과
display(df)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CTR,CPC,CVR,CPA,ROAS
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225,3.750324,173.543253,4.671280,3715.111111,721.004307
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444,7.481234,114.859532,2.898551,3962.653846,1631.039804
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303,2.545533,335.554140,10.191083,3292.625000,999.900662
3,2025-01-01,Organic,30s,Female,6866,686,81358,28,520546,9.991261,118.597668,4.081633,2905.642857,639.821530
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721,10.000000,562.000000,4.380952,12828.260870,510.327402
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,2025-06-29,Organic,20s,Female,10064,933,180066,40,814096,9.270668,192.996785,4.287245,4501.650000,452.109782
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452,9.492664,132.702048,1.303538,10180.142857,359.877072
4997,2025-06-29,Organic,40s,Male,7331,378,159162,20,795243,5.156186,421.063492,5.291005,7958.100000,499.643759
4998,2025-06-29,Google,20s,Male,9272,124,173437,23,1293372,1.337360,1398.685484,18.548387,7540.739130,745.730150
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870,5.777112,263.702592,1.773533,14868.769231,517.796724

# 전용함수

## query() 함수

In [22]:
# Channel 컬럼의 값이 'Facebook'과 같은 경우
df_facebook = df.query("Channel == 'Facebook'")
display(df_facebook)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CTR,CPC,CVR,CPA,ROAS
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225,3.750324,173.543253,4.671280,3715.111111,721.004307
5,2025-01-01,Facebook,30s,Male,11974,361,109972,39,1765516,3.014866,304.631579,10.803324,2819.794872,1605.423199
6,2025-01-01,Facebook,30s,Female,14083,155,79464,1,424394,1.100618,512.670968,0.645161,79464.000000,534.070774
8,2025-01-01,Facebook,20s,Female,15249,176,184655,1,271550,1.154174,1049.176136,0.568182,184655.000000,147.058027
9,2025-01-01,Facebook,20s,Male,6518,651,57393,27,139854,9.987726,88.161290,4.147465,2125.666667,243.677800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4981,2025-06-29,Facebook,50s+,Male,11579,546,100479,34,1181886,4.715433,184.027473,6.227106,2955.264706,1176.251754
4984,2025-06-29,Facebook,50s+,Male,8890,749,267827,37,757074,8.425197,357.579439,4.939920,7238.567568,282.672770
4986,2025-06-29,Facebook,40s,Male,14067,727,102370,45,296552,5.168124,140.811554,6.189821,2274.888889,289.686432
4988,2025-06-29,Facebook,50s+,Male,19235,973,217038,47,1704504,5.058487,223.060637,4.830421,4617.829787,785.348188
4994,2025-06-29,Facebook,30s,Male,12482,429,250816,47,330298,3.436949,584.652681,10.955711,5336.510638,131.689366

### 단일 조건 (문자열)

In [23]:
# Revenue 컬럼의 값이 1,500,000 이상인 경우
df_revenue_1500000=df.query("Revenue >= 1500000")
display(df_revenue_1500000)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CTR,CPC,CVR,CPA,ROAS
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444,7.481234,114.859532,2.898551,3962.653846,1631.039804
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303,2.545533,335.554140,10.191083,3292.625000,999.900662
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721,10.000000,562.000000,4.380952,12828.260870,510.327402
5,2025-01-01,Facebook,30s,Male,11974,361,109972,39,1765516,3.014866,304.631579,10.803324,2819.794872,1605.423199
7,2025-01-01,Google,40s,Male,14872,431,221715,17,1677619,2.898063,514.419954,3.944316,13042.058824,756.655616
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4985,2025-06-29,Google,50s+,Male,8463,846,219915,9,1987591,9.996455,259.946809,1.063830,24435.000000,903.799650
4987,2025-06-29,Naver,50s+,Female,13989,674,226994,17,1842078,4.818071,336.786350,2.522255,13352.588235,811.509555
4988,2025-06-29,Facebook,50s+,Male,19235,973,217038,47,1704504,5.058487,223.060637,4.830421,4617.829787,785.348188
4991,2025-06-29,Naver,20s,Female,8196,563,106645,36,1588784,6.869204,189.422735,6.394316,2962.361111,1489.787613
4992,2025-06-29,Google,30s,Female,15117,282,218114,31,1912754,1.865449,773.453901,10.992908,7035.935484,876.951502

### 다중조건 (논리연산자)

In [24]:
# and 연산자: 모든 조건을 동시에 만족해야 되는 경우
df3 = df.query("Channel == 'Google' and Revenue >= 1500000")
print("Channel이 Google이면서 총 매출이 1500000 이상인 행 추출")
display(df3)

Channel이 Google이면서 총 매출이 1500000 이상인 행 추출

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CTR,CPC,CVR,CPA,ROAS
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444,7.481234,114.859532,2.898551,3962.653846,1631.039804
7,2025-01-01,Google,40s,Male,14872,431,221715,17,1677619,2.898063,514.419954,3.944316,13042.058824,756.655616
12,2025-01-01,Google,50s+,Female,14972,301,50832,19,1654250,2.010419,168.877076,6.312292,2675.368421,3254.347655
13,2025-01-01,Google,40s,Female,16131,802,53791,35,1727164,4.971793,67.071072,4.364090,1536.885714,3210.879143
18,2025-01-01,Google,40s,Female,11685,287,139501,15,1777642,2.456140,486.066202,5.226481,9300.066667,1274.286206
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4938,2025-06-27,Google,50s+,Female,14760,487,276979,18,1795600,3.299458,568.745380,3.696099,15387.722222,648.280195
4944,2025-06-27,Google,20s,Female,11164,823,113620,21,1924905,7.371910,138.055893,2.551640,5410.476190,1694.160359
4979,2025-06-29,Google,20s,Female,17176,834,194693,47,1579548,4.855612,233.444844,5.635492,4142.404255,811.301896
4985,2025-06-29,Google,50s+,Male,8463,846,219915,9,1987591,9.996455,259.946809,1.063830,24435.000000,903.799650
4992,2025-06-29,Google,30s,Female,15117,282,218114,31,1912754,1.865449,773.453901,10.992908,7035.935484,876.951502

In [25]:
list_data = [3, 2, 1, 4]
del list_data[0]

print(list_data)

[2, 1, 4]

## value_counts() 함수

In [27]:
# Channel 컬럼의 항목별 빈도수 측정
channel_counts = df['Channel'].value_counts()
print(f'Channel 컬럼의 항목별 빈도수: \n{channel_counts}')

Channel 컬럼의 항목별 빈도수:
Channel
Google       1506
Facebook     1479
Naver        1023
Instagram     537
Organic       455
Name: count, dtype: int64

## merge() 함수

In [29]:
# 데이터 불러오기

## 파일 경로 설치
file_path1 = '/content/drive/MyDrive/KDT/employee.csv'
file_path2 = '/content/drive/MyDrive/KDT/salary.csv'

## DataFrame 생성
df_employee = pd.read_csv(file_path1)
df_salary = pd.read_csv(file_path2)

## 결과확인
display(df_employee)
print('-'*80)
display(df_salary)

   id name
0   1  홍길동
1   2  김철수
2   3  이영희
3   4  박민준

--------------------------------------------------------------------------------

   id  salary
0   3    3000
1   4    4000
2   5    5000
3   6    6000

In [30]:
# how = 'left'

## 왼쪽 데이터프레임 기준으로 결합
df_merge_left = pd.merge(df_employee,df_salary, on='id',how='left')
display(df_merge_left)

   id name  salary
0   1  홍길동     NaN
1   2  김철수     NaN
2   3  이영희  3000.0
3   4  박민준  4000.0

In [31]:
# how = 'right'

## 오른쪽 데이터프레임 기준으로 결합
df_merge_right = pd.merge(df_employee,df_salary, on='id',how='right')
display(df_merge_right)

   id name  salary
0   3  이영희    3000
1   4  박민준    4000
2   5  NaN    5000
3   6  NaN    6000

In [32]:
# how = 'inner'

## 양쪽에 모두 존재하는 행만 결합
df_merge_inner = pd.merge(df_employee,df_salary, on='id',how='inner')
display(df_merge_inner)

   id name  salary
0   3  이영희    3000
1   4  박민준    4000

In [33]:
# how = 'outer'

## 한쪽에만 존재하는 행도 포함해서 결합
df_merge_outer = pd.merge(df_employee,df_salary, on='id',how='outer')
display(df_merge_outer)

   id name  salary
0   1  홍길동     NaN
1   2  김철수     NaN
2   3  이영희  3000.0
3   4  박민준  4000.0
4   5  NaN  5000.0
5   6  NaN  6000.0

# 판다스(pandas) 연습문제

In [34]:
#문제 1
df= pd.read_csv('/content/drive/MyDrive/KDT/ad_performance.csv')
display(df)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303
3,2025-01-01,Organic,30s,Female,6866,686,81358,28,520546
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721
...,...,...,...,...,...,...,...,...,...
4995,2025-06-29,Organic,20s,Female,10064,933,180066,40,814096
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452
4997,2025-06-29,Organic,40s,Male,7331,378,159162,20,795243
4998,2025-06-29,Google,20s,Male,9272,124,173437,23,1293372
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870

In [35]:
#문제 2 df에서 전체 컬럼명 정보만 추출
df_columns=df.columns
print(f'DataFrame의 컬럼 인덱스 :\n {df_columns}')

DataFrame의 컬럼 인덱스 :
 Index(['Date', 'Channel', 'Age_Group', 'Gender', 'Impressions', 'Clicks',
       'Cost', 'Conversions', 'Revenue'],
      dtype='object')

In [36]:
#문제 3  세개의 컬럼만 선택하여 새로운 데이터프레임 생성
df_sub = df[['Channel','Age_Group','Revenue']]
display(df_sub)

       Channel Age_Group  Revenue
0     Facebook      50s+   723225
1       Google       20s  1680444
2        Naver      50s+  1580303
3      Organic       30s   520546
4        Naver       30s  1505721
...        ...       ...      ...
4995   Organic       20s   814096
4996     Naver       40s   256452
4997   Organic       40s   795243
4998    Google       20s  1293372
4999     Naver       30s  1000870

[5000 rows x 3 columns]

In [37]:
#문제 4 새로운 컬럼 추가: 클릭당 비용을 의미하는 'CPC' 컬럼을 추가하세요.
df['CPC']= df['Cost']/df['Clicks']
display(df)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CPC
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225,173.543253
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444,114.859532
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303,335.554140
3,2025-01-01,Organic,30s,Female,6866,686,81358,28,520546,118.597668
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721,562.000000
...,...,...,...,...,...,...,...,...,...,...
4995,2025-06-29,Organic,20s,Female,10064,933,180066,40,814096,192.996785
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452,132.702048
4997,2025-06-29,Organic,40s,Male,7331,378,159162,20,795243,421.063492
4998,2025-06-29,Google,20s,Male,9272,124,173437,23,1293372,1398.685484
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870,263.702592

In [38]:
#문제 5 데이터 필터링 (일치 조건): .query()를 사용하여 'Channel'이 'Naver'인 행들만 추출하여 출력하세요.
df_naver= df.query("Channel == 'Naver'")
display(df_naver)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CPC
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303,335.554140
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721,562.000000
25,2025-01-02,Naver,20s,Male,14492,956,173175,29,1790608,181.145397
26,2025-01-02,Naver,50s+,Female,8780,641,274416,31,1616186,428.106084
33,2025-01-02,Naver,20s,Female,17829,480,224353,47,1042465,467.402083
...,...,...,...,...,...,...,...,...,...,...
4989,2025-06-29,Naver,30s,Male,15739,832,241271,15,445842,289.989183
4990,2025-06-29,Naver,40s,Male,15270,903,62736,20,814202,69.475083
4991,2025-06-29,Naver,20s,Female,8196,563,106645,36,1588784,189.422735
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452,132.702048
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870,263.702592

In [39]:
#문제 6 데이터 필터링 (비교 조건): .query()를 사용하여 'Impressions'(노출수)가 18,000 이상인 데이터만 추출하세요.
df_18000=df.query("Impressions >= 18000")
display(df_18000)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CPC
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303,335.554140
29,2025-01-02,Google,30s,Female,18607,540,88583,7,989354,164.042593
36,2025-01-02,Facebook,30s,Female,19168,937,65293,7,1678334,69.683031
41,2025-01-02,Google,20s,Male,18662,658,208900,12,719105,317.477204
48,2025-01-02,Google,40s,Male,18187,526,272648,22,1978862,518.342205
...,...,...,...,...,...,...,...,...,...,...
4943,2025-06-27,Naver,30s,Female,19461,692,147923,40,138734,213.761561
4947,2025-06-28,Instagram,40s,Male,18752,759,284808,47,334657,375.241107
4967,2025-06-28,Facebook,50s+,Female,19822,420,61638,45,1470401,146.757143
4968,2025-06-28,Naver,20s,Male,18815,610,245035,28,1927187,401.696721
4988,2025-06-29,Facebook,50s+,Male,19235,973,217038,47,1704504,223.060637

In [40]:
#문제 7 빈도수 계산: 'Age_Group' 컬럼에 있는 각 항목별(20s, 30s 등) 데이터의 빈도수를 확인하세요.
age_counts = df['Age_Group'].value_counts('')
display(age_counts)

Age_Group
50s+    1303
20s     1269
30s     1255
40s     1173
Name: count, dtype: int64

In [41]:
#문제 8 복합 필터링 및 컬럼 선택: .query()를 사용하여 'Channel'이 'Google'이면서 'Revenue'가 1,800,000 이상인 행을 추출하고, 그 결과에서 'Date','Channel', 'Revenue' 컬럼만 선택하여 출력하세요.

In [42]:
#문제

In [43]:
# 문제 10. (종합) ROAS 컬럼 추가 후 고효율 데이터 필터링
# ROAS= 매출 / 비용 * 100
df['ROAS'] = (df['Revenue'] / df['Cost']) * 100
df2= df.query("ROAS >= 800")
display(df2)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CPC,ROAS
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444,114.859532,1631.039804
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303,335.554140,999.900662
5,2025-01-01,Facebook,30s,Male,11974,361,109972,39,1765516,304.631579,1605.423199
12,2025-01-01,Google,50s+,Female,14972,301,50832,19,1654250,168.877076,3254.347655
13,2025-01-01,Google,40s,Female,16131,802,53791,35,1727164,67.071072,3210.879143
...,...,...,...,...,...,...,...,...,...,...,...
4985,2025-06-29,Google,50s+,Male,8463,846,219915,9,1987591,259.946809,903.799650
4987,2025-06-29,Naver,50s+,Female,13989,674,226994,17,1842078,336.786350,811.509555
4990,2025-06-29,Naver,40s,Male,15270,903,62736,20,814202,69.475083,1297.822622
4991,2025-06-29,Naver,20s,Female,8196,563,106645,36,1588784,189.422735,1489.787613
4992,2025-06-29,Google,30s,Female,15117,282,218114,31,1912754,773.453901,876.951502